### ISSUE TITLE
ゲーム史、マンガ史、アニメ史を独立させたい

### ISSUE THREAD

**Issue by mikamin-in-the-wind** [shun178/internet_aged_society#10]

**Comment by masanobuimai** [comment]
#11 で、だいぶ派手にリファクタリングしたので、受け入れるかどうか任せた（捨ててもいいよ。
GitHub Pageの実行例は、ここみて。
https://masanobuimai.github.io/internet_aged_society/

**Comment by masanobuimai** [comment]
PR #11 受け入れたら，これクローズしていいでしょ（ closed #10 ）

**Comment by mikamin-in-the-wind** [comment]
クローズします
